language: java
jdk:
  - oraclejdk8

notifications:
  email: false
  slack:
    secure: RpLJBm69qkvAvCZChJPyO3pLR0buJxPycVOqlv2Zdf25UOjAHvTjr0/fYjU0A9V/nmGffvuRpsEkGkCzYBtOnRCEo9aBKnTmBOx+bnj3WqDXcItlaysNRMayDvld48vifh/i3+wu3I9kFDoBnTKBlRjZsRikEPsDdJlzdgm1EWdocTH5VC8pnCpGCabOjvglpsabrB3yDHPysS2xgcc+oDa1gHptDDxC+Ek3mWaJDXm57ULocj9+95Qi7fkfxrLSpNQqsmMKkI9IUUBtbnncp8NN/Er6Rd5awPhmXn/1PDQPCV075E0XCySm9Rv0soB0e5WOPaDxMPBOEC4UsCCoQWMgZ0TfaofO5+jnRHrQA9FxYVS4vpA4QtSDm1WwDYo7cGgYFFkNjO+ttgDb8YnTqLY2dE1GUKdQd+K4YsY8XsUkDh0LXeiIY1ZitJLDKUJCa9DdbcQW+YK2T5oMCCSaQoR5X0S8ezM/QkUZl2anXJvqWgGZtNEvxId3KfhG56lDgn2D/YoUAyDOt0s2BQQEVucT/ZSFRySfv+WgLNc1BC5Pe4kGfrjnCe7R0TZhczXOhU6Vb9yf4/O/fepNhu/n+UPTv5zR3nTbIZbn/l83+l3D1Icj5Uqu0ny/8jfvkGsBkbJSB5WW+1DHAvoNUkksdK2/cCsIiWLvs8Rd3u5SECU=
