SET SCHEMA PUBLIC;

DROP VIEW V_FEED IF EXISTS;

CREATE VIEW V_FEED AS
SELECT POST.*, TBL_FRIENDS.PERSON_ID AS FEED_USER_ID
FROM POST
JOIN TBL_FRIENDS ON POST.USER_ID=TBL_FRIENDS.FRIEND_ID
UNION
SELECT POST.*, POST.USER_ID AS FEED_USER_ID
FROM POST
ORDER BY CREATION_DATE_TIME DESC;


DROP VIEW V_USER_FEED IF EXISTS;

CREATE VIEW V_USER_FEED AS
SELECT POST.*, POST.USER_ID AS FEED_USER_ID
FROM POST
ORDER BY CREATION_DATE_TIME DESC;
